services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres:secret@db:5432/postgres?sslmode=disable
    ports:
      - 3000:3000
    depends_on:
      - db

  migrate:
    image: arigaio/atlas
    volumes:
      - ./storage/migrations:/migrations
    command: migrate apply --dir file:///migrations --url postgres://postgres:secret@db:5432/postgres?sslmode=disable
    depends_on:
      - db

volumes:
  postgres:
